"""baseline schema

Revision ID: 3573020f4493
Revises: 
Create Date: 2026-09-06 18:49:57.184641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used by the ORM models.
import app.db.base  # noqa: F401  (referenced as app.db.base.TZDateTime below)


# revision identifiers, used by Alembic.
revision: str = '3573020f4493'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('record_hash', name=op.f('uq_audit_events_record_hash'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_audit_id'), ['audit_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_sequence'), ['sequence'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_user_pk'), ['user_pk'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_sub', sa.String(length=128), nullable=False),
    sa.Column('google_email', app.db.base.EncryptedString(), nullable=False),
    sa.Column('display_name', app.db.base.EncryptedString(), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('app_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('last_used_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('expires_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('fk_app_sessions_user_pk_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_sessions'))
    )
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_sessions_user_pk'), ['user_pk'], unique=False)

    op.create_table('auth_handoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('oauth_state', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('expires_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('consumed_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('fk_auth_handoffs_user_pk_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_handoffs'))
    )
    with op.batch_alter_table('auth_handoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_handoffs_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_handoffs_user_pk'), ['user_pk'], unique=False)

    op.create_table('device_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('device_label', app.db.base.EncryptedString(), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('last_seen_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('fk_device_registrations_user_pk_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_registrations'))
    )
    with op.batch_alter_table('device_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_registrations_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_registrations_fcm_token'), ['fcm_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_registrations_user_pk'), ['user_pk'], unique=False)

    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('sender_name', app.db.base.EncryptedString(), nullable=True),
    sa.Column('sender_email', app.db.base.EncryptedString(), nullable=False),
    sa.Column('subject', app.db.base.EncryptedString(), nullable=False),
    sa.Column('snippet', app.db.base.EncryptedString(), nullable=True),
    sa.Column('received_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('final_category', sa.String(length=48), nullable=False),
    sa.Column('primary_category', sa.String(length=24), nullable=False),
    sa.Column('auto_primary_category', sa.String(length=24), nullable=False),
    sa.Column('primary_category_source', sa.String(length=8), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('priority_level', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('proximity_bucket', sa.String(length=16), nullable=False),
    sa.Column('deadline_is_past', sa.Boolean(), nullable=False),
    sa.Column('is_unread', sa.Boolean(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('viewed_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('completion_source', sa.String(length=8), nullable=False),
    sa.Column('snoozed_until', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('folder_label', sa.String(length=64), nullable=False),
    sa.Column('should_notify', sa.Boolean(), nullable=False),
    sa.Column('should_monitor', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('processed_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('fk_emails_user_pk_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails'))
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_action_required'), ['action_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_auto_primary_category'), ['auto_primary_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_email_id'), ['email_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_emails_final_category'), ['final_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_is_spam'), ['is_spam'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_is_viewed'), ['is_viewed'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_needs_human_review'), ['needs_human_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_primary_category'), ['primary_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_priority_level'), ['priority_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_user_pk'), ['user_pk'], unique=False)

    op.create_table('gmail_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('account_email', app.db.base.EncryptedString(), nullable=True),
    sa.Column('monitoring_started_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('last_sync_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('last_history_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('fk_gmail_sync_state_user_pk_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_sync_state'))
    )
    with op.batch_alter_table('gmail_sync_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmail_sync_state_user_pk'), ['user_pk'], unique=True)

    op.create_table('oauth_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('credentials_json', app.db.base.EncryptedString(), nullable=True),
    sa.Column('account_email', app.db.base.EncryptedString(), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('fk_oauth_credentials_user_pk_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_credentials'))
    )
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_credentials_user_pk'), ['user_pk'], unique=True)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_pk', sa.Integer(), nullable=False),
    sa.Column('action_ref', sa.String(length=16), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('description', app.db.base.EncryptedString(), nullable=True),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('target_link', app.db.base.EncryptedString(), nullable=True),
    sa.Column('raw_deadline_hint', app.db.base.EncryptedString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('completed_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.ForeignKeyConstraint(['email_pk'], ['emails.id'], name=op.f('fk_actions_email_pk_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions')),
    sa.UniqueConstraint('email_pk', 'action_ref', name=op.f('uq_actions_email_pk'))
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_email_pk'), ['email_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    op.create_table('classification_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('email_pk', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=128), nullable=False),
    sa.Column('original_primary_category', sa.String(length=24), nullable=False),
    sa.Column('corrected_primary_category', sa.String(length=24), nullable=False),
    sa.Column('original_final_category', sa.String(length=48), nullable=True),
    sa.Column('classifier_source', sa.String(length=32), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('email_classified_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.ForeignKeyConstraint(['email_pk'], ['emails.id'], name=op.f('fk_classification_feedback_email_pk_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], name=op.f('fk_classification_feedback_user_pk_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_feedback'))
    )
    with op.batch_alter_table('classification_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_feedback_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_feedback_email_pk'), ['email_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_feedback_user_pk'), ['user_pk'], unique=False)

    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_pk', sa.Integer(), nullable=False),
    sa.Column('deadline_ref', sa.String(length=16), nullable=False),
    sa.Column('deadline_datetime', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('source_text', app.db.base.EncryptedString(), nullable=True),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('date_only', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('ambiguity_reason', app.db.base.EncryptedString(), nullable=True),
    sa.Column('is_past', sa.Boolean(), nullable=False),
    sa.Column('action_context', sa.String(length=32), nullable=True),
    sa.Column('related_action_ref', sa.String(length=16), nullable=True),
    sa.Column('is_monitoring', sa.Boolean(), nullable=False),
    sa.Column('monitoring_started_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('monitoring_stopped_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.ForeignKeyConstraint(['email_pk'], ['emails.id'], name=op.f('fk_deadlines_email_pk_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deadlines')),
    sa.UniqueConstraint('email_pk', 'deadline_ref', name=op.f('uq_deadlines_email_pk'))
    )
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadlines_deadline_datetime'), ['deadline_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_email_pk'), ['email_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_is_monitoring'), ['is_monitoring'], unique=False)

    op.create_table('processing_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_pk', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('processed_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('final_category', sa.String(length=48), nullable=False),
    sa.Column('priority_level', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('agent_trace', sa.JSON(), nullable=False),
    sa.Column('conflicts_resolved', sa.JSON(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.ForeignKeyConstraint(['email_pk'], ['emails.id'], name=op.f('fk_processing_runs_email_pk_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_runs'))
    )
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_runs_email_pk'), ['email_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_runs_run_id'), ['run_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_pk', sa.Integer(), nullable=False),
    sa.Column('action_ref', sa.String(length=16), nullable=True),
    sa.Column('reminder_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('reminder_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('note', app.db.base.EncryptedString(), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('triggered_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('cancelled_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.ForeignKeyConstraint(['email_pk'], ['emails.id'], name=op.f('fk_reminders_email_pk_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_email_pk'), ['email_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_reminder_at'), ['reminder_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_pk', sa.Integer(), nullable=False),
    sa.Column('deadline_pk', sa.Integer(), nullable=True),
    sa.Column('reminder_pk', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=48), nullable=False),
    sa.Column('reminder_level', sa.String(length=16), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('requires_alarm', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', app.db.base.EncryptedString(), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(length=40), nullable=False),
    sa.Column('sent_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('pushed_at', app.db.base.TZDateTime(length=40), nullable=True),
    sa.Column('push_status', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['deadline_pk'], ['deadlines.id'], name=op.f('fk_notifications_deadline_pk_deadlines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_pk'], ['emails.id'], name=op.f('fk_notifications_email_pk_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_pk'], ['reminders.id'], name=op.f('fk_notifications_reminder_pk_reminders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_deadline_pk'), ['deadline_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_email_pk'), ['email_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_email_pk'))
        batch_op.drop_index(batch_op.f('ix_notifications_deadline_pk'))

    op.drop_table('notifications')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_reminder_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_email_pk'))

    op.drop_table('reminders')
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_processing_runs_email_pk'))

    op.drop_table('processing_runs')
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadlines_is_monitoring'))
        batch_op.drop_index(batch_op.f('ix_deadlines_email_pk'))
        batch_op.drop_index(batch_op.f('ix_deadlines_deadline_datetime'))

    op.drop_table('deadlines')
    with op.batch_alter_table('classification_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_feedback_user_pk'))
        batch_op.drop_index(batch_op.f('ix_classification_feedback_email_pk'))
        batch_op.drop_index(batch_op.f('ix_classification_feedback_email_id'))

    op.drop_table('classification_feedback')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_status'))
        batch_op.drop_index(batch_op.f('ix_actions_email_pk'))

    op.drop_table('actions')
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_credentials_user_pk'))

    op.drop_table('oauth_credentials')
    with op.batch_alter_table('gmail_sync_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmail_sync_state_user_pk'))

    op.drop_table('gmail_sync_state')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_user_pk'))
        batch_op.drop_index(batch_op.f('ix_emails_priority_level'))
        batch_op.drop_index(batch_op.f('ix_emails_primary_category'))
        batch_op.drop_index(batch_op.f('ix_emails_needs_human_review'))
        batch_op.drop_index(batch_op.f('ix_emails_is_viewed'))
        batch_op.drop_index(batch_op.f('ix_emails_is_spam'))
        batch_op.drop_index(batch_op.f('ix_emails_is_completed'))
        batch_op.drop_index(batch_op.f('ix_emails_final_category'))
        batch_op.drop_index(batch_op.f('ix_emails_email_id'))
        batch_op.drop_index(batch_op.f('ix_emails_auto_primary_category'))
        batch_op.drop_index(batch_op.f('ix_emails_action_required'))

    op.drop_table('emails')
    with op.batch_alter_table('device_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_registrations_user_pk'))
        batch_op.drop_index(batch_op.f('ix_device_registrations_fcm_token'))
        batch_op.drop_index(batch_op.f('ix_device_registrations_active'))

    op.drop_table('device_registrations')
    with op.batch_alter_table('auth_handoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_handoffs_user_pk'))
        batch_op.drop_index(batch_op.f('ix_auth_handoffs_code_hash'))

    op.drop_table('auth_handoffs')
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_sessions_user_pk'))
        batch_op.drop_index(batch_op.f('ix_app_sessions_token_hash'))

    op.drop_table('app_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))

    op.drop_table('users')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_pk'))
        batch_op.drop_index(batch_op.f('ix_audit_events_sequence'))
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_audit_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
